### ISSUE TITLE
Missing Dependency - github.com/go-gonzo/angular-templatecache

### ISSUE THREAD

**Issue by ermergerd** [omeid/golang-angular-material#1]
I grabbed this project to play around with it, but I found that one of the dependencies ("github.com/go-gonzo/angular-templatecache") does not exist.  I searched github a bit and found what I think is its predecessor - github.com/slurp-contrib/angular-templatecache).  Any way you could get the referenced project uploaded?  Thanks!

**Comment by omeid** [comment]
Whops. I forgot to push it to github. Just pushed it now. Please let me know if you end-up with any other issue!
