### ISSUE TITLE
"kar install -x -v" fails with msg "cannot find package"

### ISSUE THREAD

**Issue by arafath-mk** [omeid/golang-angular-material#3]
I am using *go version go1.8beta1* in Windows 10; 64 bit.

```bash
F:\Temp\sample\src\github.com\omeid\golang-angular-material>kar install -x -v

time="2016-12-09T17:49:40+05:30" level=fatal msg="cannot find package \"golang_org/x/crypto/chacha20poly1305\" in any of:\n\tC:\\Go\\src\\golang_org\\x\\crypto\\chacha20poly1305 (from $GOROOT)\n\tF:\\Temp\\sample\\src\\golang_org\\x\\crypto\\chacha20poly1305 (from $GOPATH)"
```
It is strange that, it is complaining about *golang_org* instead of *golang.org*

Here is the output of *go env* command. I am using Windows 10; 64 bit OS.

```bash
F:\Temp\sample\src\github.com\omeid\golang-angular-material>go env
set GOARCH=amd64
set GOBIN=F:\Temp\sample\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\Temp\sample
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\FIRMUS~1\AppData\Local\Temp\go-build198880131=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

**Comment by omeid** [comment]
What does `go get -x -v` reports?

**Comment by arafath-mk** [comment]
Thanks @omeid 
Now `kar get -x -v` run without any issues. But `kar install -x -v` ends with error. Below is the output.

```bash
F:\Temp\sample\src\github.com\omeid\golang-angular-material>kar install -x -v

time="2016-12-10T12:17:02+05:30" level=fatal msg="cannot find package \"golang_org/x/crypto/chacha20poly1305\" in any of:\n\tC:\\Go\\src\\golang_org\\x\\crypto\\chacha20poly1305 (from $GOROOT)\n\tF:\\Temp\\sample\\src\\golang_org\\x\\crypto\\chacha20poly1305 (from $GOPATH)"
```

**Comment by omeid** [comment]
Looks go `1.8` is doing some vendoring with `golang.org` packages and such.

Can you nuke your `$GOPATH/pkg` (because you may still have packages built with your previous version of Go which doesn't understand this weird vendoring) and try again?

**Comment by arafath-mk** [comment]
Hi @omeid,
Still not working. Same error as previous.

**Comment by alanef** [comment]
Same issue for me ( on mac OS )

$GOPATH/bin/kar install -x -v

FATA[0000] cannot find package "golang_org/x/net/route" in any of:
	/usr/local/go/src/golang_org/x/net/route (from $GOROOT)

**Comment by omeid** [comment]
Hi @alanef,

Are you also using Go 1.8?

**Comment by alanef** [comment]
go version go1.7 darwin/amd64

**Comment by omeid** [comment]
Yo, so this should be fixed. Just do a `go get -u github.com/omeid/kar/cmd/kar` and you should be good to go.

This issue was introduce in Go 1.6 with http package vendoring x/net but conflicting with `user-space` (library consumer) vendoring and they came up with a weird workaround, that requires a workaround. 😕
